---
- name: Run auto tests for modules
  hosts: localhost
  gather_facts: no
  vars:
    module_name: LIS-frontend
    telegram_token: 5123724065:AAGHlvxmC68yGHeBSf7l61aNDuMq51igR7E
    chat_id: -705242438
  tasks:
    - name: run tests and push message to telegram
      block:
        - name: install playwright and run tests
          ansible.builtin.shell: |
            cd ..
            npm install
            npm run test:core
        #     npx playwright install
        #     npx playwright test


        # - name: Notify Telegram
        #   uri:
        #     url: "https://api.telegram.org/bot{{telegram_token}}/sendMessage"
        #     method: POST
        #     body: {
        #       "chat_id": "{{chat_id}}",
        #       "text": "
        #         В репозиторий Nexus опубликована новая версия пакета {{ package_name }}\n",
        #       "parse_mode": Markdown
        #     }
        #     body_format: json
        #     headers:
        #       Content-Type: "application/json"

      delegate_to: localhost
